#!/bin/bash

echo "=> Run Ansible"
fail_provision=0
ansible-playbook test.yml --connection=local
rc=$?
if [[ $rc != 0 ]]; then
    echo "=> PROVISIONING FAIL"
    fail_provision=1
fi

if [[ $fail_provision == 1 ]]; then
    echo "=> FAIL FAIL FAIL"
    exit 1
else
    echo "=> SUCCESS"
fi
