---

- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest
    
- name: Enable service httpd, and not touch the running state
  service:
    name: httpd
    enabled: yes
